### ISSUE TITLE
Problem installing from github

### ISSUE THREAD

**Issue by sarahhcarl** [KChen-lab/SCMarker#2]
Hi there,
I'm quite keen to test out SCMarker; however, when I try to install it from github using devtools, it fails with the following error:

```
Error : (converted from warning) /tmp/RtmpqxidqW/R.INSTALL6a8b4f4b65c4/SCMarker/man/HeatmapCluster.Rd:86: unexpected END_OF_INPUT '}
'
ERROR: installing Rd objects failed for package ‘SCMarker’
* removing ‘/home/common/BioC/R-3.6.0-release_BioC-3.9-release/SCMarker’
Error: Failed to install 'SCMarker' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpGawVqT/file2f54df03bb4/SCMarker_2.0.tar.gz’ had non-zero exit status
```

Looks like a problem with some of the documentation? I also tried download the tar.gz source code, but I got the same error.

Thanks for the help!
Sarah

**Comment by Fang0828** [comment]
SCMarker was packaged under R/3.4 or R/3.5. Can you try install it under this environment? We'll update SCMarker to the latest R version later.
