### ISSUE TITLE
Usage with integrated data?

### ISSUE THREAD

**Issue by hummuscience** [KChen-lab/SCMarker#4]
I was wondering if it is possible to use your package with embedding (integrated data), such as the output from Harmony.

If yes, could you explain how?

**Comment by Fang0828** [comment]
I think so. You can extract integrated data from Harmony as input data for SCMarker.

**Comment by hummuscience** [comment]
Harmony does not generate corrected counts, only a corrected embedding (PCA) that can be used for clustering.

**Comment by Fang0828** [comment]
SCMarker selects gene feature to help clustering instead of PCA feature. It can't be applied on PCA data.

**Comment by hummuscience** [comment]
Thank you for the information :) This answers my question
